### ISSUE TITLE
transaction_input.type & transaction_input.value are null

### ISSUE THREAD

**Issue by tokusyu** [blockchain-etl/bitcoin-etl#14]
On my environment, the field "type" & "value" at transaction_input are always null.
like,
"inputs": [{"index": 0, "spent_transaction_hash": "100a776847c80201ca6efa5605b806ec770c105af95972eb522e45af385b3892", "spent_output_index": 0, "script_asm": "3045022100b61b8132060e810387518dbd697f731eb1680debf3882ed04821a5d54ced2bca022017a5356096f7db93d9b989114e248476d37325aab7ebc2a8f5800a2e9e6a6618[ALL] 047bade8836f9ccd1923851351e70683606d86a22b6c78676ea3eae343aff5c8c3964e39c9edcf11807949bd325c9475b14de3dcd91b354a7e9d64a0e9b3e10f6b", "script_hex": "483045022100b61b8132060e810387518dbd697f731eb1680debf3882ed04821a5d54ced2bca022017a5356096f7db93d9b989114e248476d37325aab7ebc2a8f5800a2e9e6a66180141047bade8836f9ccd1923851351e70683606d86a22b6c78676ea3eae343aff5c8c3964e39c9edcf11807949bd325c9475b14de3dcd91b354a7e9d64a0e9b3e10f6b", "type": null, "sequence": 4294967295, "value": null},

I know, Getting these values requires another RPC "getrawtransaction" and bitcoin-cli with "getrawtransaction" returns these values on my environment.
Has "getrawtransaction" not been implemented?

I'm using bitcoinetl, version 1.1.0, installed from pip.

**Comment by medvedev1088** [comment]
In production the filling of values and types for inputs is done in BigQuery. This way it's much faster comparing to using "getrawtransaction" API. For streaming support I added a separate job for enriching inputs https://github.com/blockchain-etl/bitcoin-etl/pull/13/files#diff-106eff54cb1914c328632ce63ebf3cb8

**Comment by tokusyu** [comment]
I got it.
I will try a job enriching inputs, thanks.

**Comment by medvedev1088** [comment]
I added enrich_transactions command https://github.com/blockchain-etl/bitcoin-etl#enrich_transactions

**Comment by tokusyu** [comment]
Thanks!
It worked perfectly.

And it would be nice if this command is integrated into export_all command as parameter.

**Comment by medvedev1088** [comment]
Published to pypi https://pypi.org/project/bitcoin-etl/1.3.0/

https://github.com/blockchain-etl/bitcoin-etl/releases/tag/v1.3.0
