### ISSUE TITLE
Zcash dataset ignores Sapling pool when calculating fees

### ISSUE THREAD

**Issue by str4d** [blockchain-etl/bitcoin-etl#23]
For transactions containing Sapling shielded inputs or outputs, a single fake input or output is added to the transaction representing the net migration of funds into or out of the Sapling pool.

https://github.com/blockchain-etl/bitcoin-etl/blob/23877a54f90536bc2fe817490661efbd07d97be9/bitcoinetl/service/btc_service.py#L177-L187

However, this fake input or output is not included in the fee calculation, causing fees to appear massively inflated in some cases. Looking at the transaction implementation, the fee _should_ include the fake input or output:

https://github.com/blockchain-etl/bitcoin-etl/blob/23877a54f90536bc2fe817490661efbd07d97be9/bitcoinetl/domain/transaction.py#L45-L71

My guess is that this is an ordering problem: the fee is being cached somewhere before the fake input or output is added. I can't see where that is happening though.

As an example, BigQuery says that transaction `13d78b6036aa5be6646c4fa96e3a779eb03f82fdc226e7cf82a9197d28d03a6b` has a fee of 294206950000 zatoshis, when it was really 0.0001 ZEC (10,000 zatoshis) according to a blockchain explorer. However, it returns `inputs.value = 147103480000` and `outputs.value = -147103470000`, and adding these together gives the real fee.

**Comment by Mitchellpkt** [comment]
I've been adding `SELECT ... ABS(ABS(input_value) - ABS(output_value)) as real_fee ...` as a workaround for non-coinbase transactions, but this only produces the correct value for transactions whose entire amount enters the shielded pool.

**Comment by Mitchellpkt** [comment]
As a quick note from my own EDA:
-  **Transparent >> Transparent** `fee` is calculated correctly
-  **Shielded >> Shielded** always shows `fee=0`
-  **Transparent >> Shielded** produces anomaly (can work around with above snippet)
-  **Transparent >> {mixed}** produces anomaly that is not as straightforward to correct

**Comment by medvedev1088** [comment]
@str4d It seems I missed the negation here:

```
if transaction.value_balance > 0: 
    input = BtcTransactionInput() 
    input.type = ADDRESS_TYPE_SHIELDED 
    input.value = transaction.value_balance 
    transaction.add_input(input) 
if transaction.value_balance < 0: 
    output = BtcTransactionOutput() 
    output.type = ADDRESS_TYPE_SHIELDED 
    output.value = -transaction.value_balance              <---------- the minus sign is missing
    transaction.add_output(output) 
```

With this fix the fee calculation should be correct.

@Mitchellpkt could you provide an example for this case

> Transparent >> {mixed} produces anomalous value that is not as straightforward to correct

**Comment by medvedev1088** [comment]
Fixed in BigQuery dataset. Let me know if you find any other issues.

**Comment by Mitchellpkt** [comment]
@medvedev1088 Thanks! Looks great, seems to be returning correct values now. :- )
