### ISSUE TITLE
How to speed up the enrich process

### ISSUE THREAD

**Issue by jsvisa** [blockchain-etl/bitcoin-etl#31]
In the export_all process, seems the enriching process took the most time, how to speed up this process?

**Comment by medvedev1088** [comment]
You are right, it's a very time consuming operation. For the historical export I disable enrichment during export and do the enrichment afterwards in BigQuery. This is the SQL I use in my Airflow DAG: https://github.com/blockchain-etl/bitcoin-etl-airflow/blob/master/dags/resources/stages/enrich/sqls/transactions.sql. It runs for just a few minutes. The enriched transactions can then be exported to JSON files in GCS.

**Comment by jsvisa** [comment]
Thanks, by now, I pop All the UTXO outputs into Redis as cache,  so every input may be found in the Redis cache, this speed the whale process.
