### ISSUE TITLE
rpc error of bitcoinetl enrich_transactions

### ISSUE THREAD

**Issue by SuperLSH** [blockchain-etl/bitcoin-etl#42]
@medvedev1088 Hi,
I want to  get the values of transactions inputs.  so I use enrich_transactions.
An error occurred at runtime:
  File "..../bitcoinetl/rpc/bitcoin_rpc.py", line 53, in batch
    raise ValueError('"result" is None in the JSON RPC response {}. Request: {}', resp_item.get('error'), text)
ValueError: ('"result" is None in the JSON RPC response {}. Request: {}', {'code': -5, 'message': '**No such mempool transaction. Use -txindex or provide a block hash to enable blockchain transaction queries. Use gettransaction for wallet transactions**.'}, 
'[{"jsonrpc": "2.0", "method": "**getrawtransaction**", "params": ["899652e48f685736a1b9af0d2db2e64a906d74064b79650c173b85073aac5d4f", 1], "id": "1"}, 
...
It dosen't seem to be a problem of bitcoin core.
I will appreciate it if you can give me some advice!
Thank you very much!!

**Comment by medvedev1088** [comment]
Could you provide the entire command that you ran as well as the prior export_blocks_and_transactions command.

**Comment by SuperLSH** [comment]
> Could you provide the entire command that you ran as well as the prior export_blocks_and_transactions command.
1. bitcoinetl export_blocks_and_transactions --start-block 620000 --end-block 620099 \
> --provider-uri  http://user:passport@localhost:8332 \
> --blocks-output ../bitcoin/btest2.json \
> --transactions-output ../bitcoin/ttest2.json \
> --chain bitcoin
2. bitcoinetl enrich_transactions    --provider-uri http://user:passport@localhost:8332   --transactions-input ttest2.json --transactions-output enriched_ttest2.json

And the same error also appears when running:
bitcoinetl export_all --start 620010 --end 620019 \
> --partition-batch-size 10 \
> --provider-uri http://user:passport@localhost:8332 \
> --output-dir../bitcoin \
> --chain bitcoin \
> --enrich true

**Comment by SuperLSH** [comment]
@medvedev1088 
Other information:
Bitcoin Core version v0.19.99.0-41fa292
bitcoinetl, version 1.4.0
thanks!

**Comment by medvedev1088** [comment]
That's weird I can't reproduce this issue. Both commands run fine for me. I used bitcoin 0.19.1 from dockerhub https://hub.docker.com/r/blockchainetl/bitcoind and bitcoin-etl from master:

```
git clone https://github.com/blockchain-etl/bitcoin-etl.git

docker build -t bitcoin-etl:latest .

docker run -v $HOME/output:/bitcoin-etl/output bitcoin-etl:latest export_blocks_and_transactions --start-block 620000 --end-block 620099 \
    --provider-uri http://localhost:3389 --blocks-output output/blocks.json --transactions-output output/transactions.json


docker run -v $HOME/output:/bitcoin-etl/output bitcoin-etl:latest enrich_transactions --provider-uri http://localhost:3389 --transactions-input output/transactions.json --transactions-output output/enriched_ttest2.json
```

**Comment by SuperLSH** [comment]
Thanks for your help!!!!
I just found the problem. Because I didn't set txindex=1...
I'm sorry to have taken up your time!

**Comment by etiennekintzler** [comment]
I had the exact same issue, solved by setting txindex=1. 

@medvedev1088  what do you think of adding something like 'This command assume that you're running bitcoin daemon with the option txindex=1' in the [enrich_transactions section of the README.md](https://github.com/blockchain-etl/bitcoin-etl#enrich_transactions) ?

**Comment by medvedev1088** [comment]
> I had the exact same issue, solved by setting txindex=1.
> 
> @medvedev1088 what do you think of adding something like 'This command assume that you're running bitcoin daemon with the option txindex=1' in the [enrich_transactions section of the README.md](https://github.com/blockchain-etl/bitcoin-etl#enrich_transactions) ?

Thanks, updated the README now.
